/*
 * version.h — Picocalc_NESco system-wide version information
 *
 * System version is managed intentionally by the project.
 * PICOCALC_NESCO_VERSION is bumped for releases or significant checkpoints.
 * Build id changes on every compile so hardware logs can distinguish binaries.
 */

#pragma once

#define PICOCALC_NESCO_VERSION "1.2.3"
#define PICOCALC_NESCO_BUILD_ID __DATE__ " " __TIME__

#ifdef NESCO_MAPPER19_N163_ONLY_DIAGNOSTIC
#define PICOCALC_NESCO_BUILD_VARIANT "N163-ONLY"
#elif defined(NESCO_MAPPER19_N163_MUTE_DIAGNOSTIC)
#define PICOCALC_NESCO_BUILD_VARIANT "N163-MUTE"
#elif defined(NESCO_AUDIO_HIGH_PRIORITY) && defined(NESCO_AUDIO_RAMFUNC) && defined(NESCO_AUDIO_DMA64)
#define PICOCALC_NESCO_BUILD_VARIANT "AUDIO-HIGH-RAM-DMA64"
#elif defined(NESCO_AUDIO_HIGH_PRIORITY)
#define PICOCALC_NESCO_BUILD_VARIANT "AUDIO-HIGH"
#elif defined(NESCO_AUDIO_RAMFUNC) && defined(NESCO_AUDIO_DMA64)
#define PICOCALC_NESCO_BUILD_VARIANT "AUDIO-RAM-DMA64"
#elif defined(NESCO_AUDIO_RAMFUNC)
#define PICOCALC_NESCO_BUILD_VARIANT "AUDIO-RAM"
#elif defined(NESCO_AUDIO_DMA64)
#define PICOCALC_NESCO_BUILD_VARIANT "AUDIO-DMA64"
#elif defined(NESCO_AUDIO_HSYNC_BATCH)
#define PICOCALC_NESCO_BUILD_VARIANT "AUDIO-BATCH"
#else
#define PICOCALC_NESCO_BUILD_VARIANT "STANDARD"
#endif

#define PICOCALC_NESCO_DISPLAY_LABEL \
    "V" PICOCALC_NESCO_VERSION " " PICOCALC_NESCO_BUILD_VARIANT
#define PICOCALC_NESCO_MENU_LABEL \
    "NESco " PICOCALC_NESCO_DISPLAY_LABEL
#define PICOCALC_NESCO_BANNER "PicoCalc NESco Ver. " PICOCALC_NESCO_VERSION
#define PICOCALC_NESCO_BANNER_FULL \
    PICOCALC_NESCO_BANNER " " PICOCALC_NESCO_BUILD_VARIANT " Build " PICOCALC_NESCO_BUILD_ID
